analytics:
  googleId: ''

bylineFormat: name-title # name | name-title | false

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: false
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'epub-cover.png'
  outputDir: '_epub'

footnotes:
  backlinkSymbol: '↩'

figures:
  assetDir: '/_assets/'
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '
